### ISSUE TITLE
(null)

### ISSUE THREAD

**Issue by ghost** [bartholomej/csfd-magnets#36]
(null)

**Comment by bartholomej** [comment]
@eladkarako Sorry for the very late reply. I forgot. 🙈 😊
In my experience, all proxies and single service instances get shut down very frequently. 
Even these two links don't work anymore.

The app uses a provider that has been working for years.

Do you have a tip on any others?

**Comment by eladkarako** [comment]
do yourself a favor and pre-disable javascript in `chrome://settings/content/javascript` for all of those. they work fine w/o js and you won't get a ton of click-handlers that opens popups. the core sites are fine to scrape.

https://thepiratebay.zone/
https://pirateproxy.live/
https://proxybay.github.io/
https://pirateproxy.wtf/
https://piratebayproxy.info/
https://thepiratebay10.org/
https://piratebay-proxylist.com/

**Comment by bartholomej** [comment]
Version 1.16.0 now uses fallback to the other two providers from your list.

You can already test this in Chrome, when you update to the new version.

Let me know.
